// <auto-generated />
using System;
using CRM.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.API.Migrations
{
    [DbContext(typeof(KlantenDbContext))]
    [Migration("20260324115509_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Models.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HuisNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Straat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LandCode");

                    b.ToTable("Adressen");
                });

            modelBuilder.Entity("CRM.Models.Factuur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BetaalStatus")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FactuurDatum")
                        .HasColumnType("date");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<decimal>("Prijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("TeBetalenVoor")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Facturen");
                });

            modelBuilder.Entity("CRM.Models.FactuurLijn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BrutoPrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BtwPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FactuurId")
                        .HasColumnType("int");

                    b.Property<decimal>("NettoPrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactuurId");

                    b.ToTable("FactuurLijnen");
                });

            modelBuilder.Entity("CRM.Models.GebruikersAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AanmaakDatum")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("int");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("GebruikersAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AanmaakDatum = new DateOnly(2026, 3, 24),
                            Email = "admin@admin.com",
                            SecurityLevel = 1,
                            Wachtwoord = "$2a$11$PE6KLR6iBRArcrrmg5Q3I.CeBU6YbTscN/nelbDhmhOchiDmqECaq"
                        },
                        new
                        {
                            Id = 2,
                            AanmaakDatum = new DateOnly(2026, 3, 24),
                            Email = "owner@owner.com",
                            SecurityLevel = 2,
                            Wachtwoord = "$2a$11$ETni2NLh0lIWizHEYV5k4OTSD5vSoQZXs5/ml1Cxz3.iv/m1eJ9zq"
                        },
                        new
                        {
                            Id = 3,
                            AanmaakDatum = new DateOnly(2026, 3, 24),
                            Email = "user@user.com",
                            SecurityLevel = 0,
                            Wachtwoord = "$2a$11$XJbsMCPJ4CAJMT0KD.0yLOlTGnhAn97IP.BLATYzBBdvV7W9LdhU2"
                        });
                });

            modelBuilder.Entity("CRM.Models.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aanspreking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdresId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("GeboorteDatum")
                        .HasColumnType("date");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoonNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("CRM.Models.Land", b =>
                {
                    b.Property<string>("LandCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LandNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LandCode");

                    b.ToTable("Landen");

                    b.HasData(
                        new
                        {
                            LandCode = "BE",
                            LandNaam = "België"
                        },
                        new
                        {
                            LandCode = "FR",
                            LandNaam = "Frankrijk"
                        },
                        new
                        {
                            LandCode = "NL",
                            LandNaam = "Nederland"
                        },
                        new
                        {
                            LandCode = "DE",
                            LandNaam = "Duitsland"
                        },
                        new
                        {
                            LandCode = "EN",
                            LandNaam = "Engeland"
                        });
                });

            modelBuilder.Entity("CRM.Models.Adres", b =>
                {
                    b.HasOne("CRM.Models.Land", "Land")
                        .WithMany()
                        .HasForeignKey("LandCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Land");
                });

            modelBuilder.Entity("CRM.Models.Factuur", b =>
                {
                    b.HasOne("CRM.Models.Klant", "Klant")
                        .WithMany("Facturen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("CRM.Models.FactuurLijn", b =>
                {
                    b.HasOne("CRM.Models.Factuur", "Factuur")
                        .WithMany("FactuurLijnen")
                        .HasForeignKey("FactuurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factuur");
                });

            modelBuilder.Entity("CRM.Models.Klant", b =>
                {
                    b.HasOne("CRM.Models.Adres", "Adres")
                        .WithMany()
                        .HasForeignKey("AdresId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("CRM.Models.Factuur", b =>
                {
                    b.Navigation("FactuurLijnen");
                });

            modelBuilder.Entity("CRM.Models.Klant", b =>
                {
                    b.Navigation("Facturen");
                });
#pragma warning restore 612, 618
        }
    }
}
